apiVersion: v2
appVersion: 0.61.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Helm chart to deploy airbyte-server
name: server
type: application
version: 0.94.1
